### ISSUE TITLE
pytorch_lightning.loggers import LightningLoggerBase

### ISSUE THREAD

**Issue by zxkathy** [Lightning-Universe/lightning-bolts#972] opened 2023-02-04 00:47 UTC
In data_monitor.py
```
pytorch_lightning.loggers import LightningLoggerBase
```
I always get the error message cannot import name 'LightningLoggerBase' from 'pytorch_lightning.loggers'

but would be working if 
```
from pytorch_lightning.loggers.base import LightningLoggerBase
```

Or if you update latest pytorch_lightning, they removed LightningLoggerBase completely, and use something else simpler.

**Comment by senarvi** [comment] 2023-02-24 16:40
This is a duplicate of https://github.com/Lightning-AI/lightning-bolts/issues/962

**Comment by devdastl** [comment] 2023-04-13 15:48
Is this issue solved? I can still see `LightningModule` in `data_monitor.py`

**Comment by tedtroxell** [comment] 2023-04-18 16:49
@devdastl there's a PR that's been out for a little bit. I'm hoping that we can get it merged ASAP

**Closed** 2023-05-11 15:59 UTC
Labels: help wanted
